version: '3.8'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - pi-client
      - pi-service
  pi-client:
    build: ./piClient
    image: pi-client:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
  pi-service:
    build: ./piService
    image: pi-service:latest
    restart: unless-stopped
    ports:
      - "31415:31415"
