apiVersion: v1
kind: Service
metadata:
  name: pi-service-service
spec:
  type: ClusterIP
  selector:
    app: pi-service
  ports:
    - name: pi-service-service-port
      protocol: TCP
      port: 31415
      targetPort: pi-service-port
