const { exit } = require('process');
const yargs = require('yargs');
const fs = require('fs');

const argv = yargs
  .option('env', {
    alias: 'e',
    description: 'Set the build environment to "production" or "development"',
    type: 'string',
  })
  .help()
  .alias('help', 'h').argv;

if (!argv.env) {
  console.error('env option is missing');
  exit(-1);
}

switch (argv.env) {
  case 'production':
    fs.copyFileSync('.env.production', '.env');
    break;
  case 'development':
    fs.copyFileSync('.env.development', '.env');
    break;
  default:
    console.error('env option should be set to "production" or "development"');
    exit(-1);
}
const data = fs.readFileSync('.env');
const fd = fs.openSync('.env', 'w+');
const insert = Buffer.from('# This file is auto-generated by ./script/prebuild.ts. \n# Do not change it manually!\n');
fs.writeSync(fd, insert, 0, insert.length, 0);
fs.writeSync(fd, data, 0, data.length, insert.length);
fs.close(fd, (err) => {
  if (err) throw err;
});
console.log('.env.' + argv.env + ' copied');
exit(0);
