# This is a basic workflow to help you get started with Actions

name: Release & Deploy

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-push:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Add latest tag
      - name: Add latest tag
        run: |
          sed -i -E 's/(\ *)(# )(tags:)/\1\3/' docker-compose.yml
          sed -i -E '/tags:/{n;s/(\ *)(# )(.*)/\1\3/}' docker-compose.yml

      - name: Build the Docker images
        run: docker compose build

      - name: Push the Docker images
        run: |
          docker push -a rssws/pi-client
          docker push -a rssws/pi-service

  deploy:
    runs-on: ubuntu-latest
    needs: [build-and-push]
    steps:
      - uses: actions/checkout@v4

      - name: Create SSH private key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/private
          sudo chmod 600 ~/.ssh/private
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}

      - name: Replace version in .env.prod
        run: |
          ssh -i ~/.ssh/private -t ${{ secrets.DEPLOY_SSH_HOSTNAME }} -p ${{ secrets.DEPLOY_SSH_PORT }} -o StrictHostKeyChecking=no \
            " \
            cd ${{ secrets.DEPLOY_FOLDER }} && \
            sed -i 's/VERSION=.*/'"$(cat .env | grep VERSION)"'/g' .env.prod \
            "

      - name: Pull the latest repository and docker images
        run: |
          ssh -i ~/.ssh/private -t ${{ secrets.DEPLOY_SSH_HOSTNAME }} -p ${{ secrets.DEPLOY_SSH_PORT }} -o StrictHostKeyChecking=no \
            " \
            cd ${{ secrets.DEPLOY_FOLDER }} && \
            git checkout main && \
            git pull && \
            docker compose --env-file=.env.prod pull \
            "

      - name: Run the latest images
        run: |
          ssh -i ~/.ssh/private -t ${{ secrets.DEPLOY_SSH_HOSTNAME }} -p ${{ secrets.DEPLOY_SSH_PORT }} -o StrictHostKeyChecking=no \
            " \
            cd ${{ secrets.DEPLOY_FOLDER }} && \
            docker compose --env-file=.env.prod up -d --remove-orphans --force-recreate \
            "
